version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: simple_shop
    ports:
      - 3306:3306
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
